FROM rust:1.69.0-buster

RUN apt-get update && apt-get install -y \
  build-essential \
  clang \
  libclang-dev \
  cmake \
  libprotobuf-dev \
  protobuf-compiler \
  libsuitesparse-dev \
  libeigen3-dev \
  curl \
  git
