FROM rust:1.74.0-bookworm

RUN apt-get update && apt-get install -y \
  lldb \
  build-essential \
  clang \
  libclang-dev \
  cmake \
  libprotobuf-dev \
  protobuf-compiler \
  libsuitesparse-dev \
  libeigen3-dev \
  curl \
  git
