name: Verify Build
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout dss_rs
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Get FPC
        run: "sudo apt install fpc && fpc -iV"

      - name: Build dss_rs
        run: rustup default nightly && cargo build --release

      - name: Build dss_capi
        run: "cd dss_rs_sys && \
              mkdir -p klusolvex && \
              cp klusolve/LICENSE klusolvex/LICENSE && \
              cd dss_capi && \
              build/build_linux_x64.sh && \
              cp lib/linux_x64/*.so /usr/local/lib/"

      - name: Test dss_rs
        run: cargo test -- --test-threads 1